### PR TITLE
[Fix-158] fix application filter for mentors

### LINKED ISSUE #158: Fix filters on viewing mentor applications
When logged in as admin, on mentor applications filters are not working.

### PR DESCRIPTION
**Pull request by AnastasiaDevs**

### CODE REVIEW

File: src/pages/ApplicationsPage/ui/ApplicationsPage.tsx [hunk 1]
```diff
@@ -9,15 +9,39 @@ import { signOut } from 'firebase/auth';
...
-  const [filter, setFilter] = useState<string>('All');
+  const [mentorApplications, setMentorApplications] = useState<MentorApplication[]>([]);
+  const [filter, setFilter] = useState<FilterLabel>('All');
   const [filterType, setFilterType] = useState<string>('Members');
   const navigate = useNavigate();
 
+  
+  const filterByStatus = <T extends { status: string }>(applications: T[] , filter: FilterLabel) => {
+
+    const statusMap: Record<Exclude<FilterLabel, 'All'>, Status> = {
```
Comment (yellalena) [inline src/pages/ApplicationsPage/ui/ApplicationsPage.tsx]: can the statusMap be a file-level const instead of being re-created on each method call?

File: src/pages/ApplicationsPage/ui/ApplicationsPage.tsx [hunk 2]
```diff
@@ -26,27 +50,8 @@ export const ApplicationsPage = () => {
...
-              )
-            );
-          } else if (filter === 'Rejected') {
-            setApplications(
-              res.data.applications.filter(
-                (application: Application) => application.status === 'rejected'
-              )
-            );
-          }
+          setApplications(filterByStatus<Application>(res.data.applications, filter));
```
Comment (yellalena) [inline src/pages/ApplicationsPage/ui/ApplicationsPage.tsx]: what happens if the api returned non-200 here / `applications` is missing in response?

File: src/pages/ApplicationsPage/ui/ApplicationsPage.tsx [hunk 3]
```diff
@@ -60,7 +65,7 @@ export const ApplicationsPage = () => {
 
           getMentors()
             .then((res) => {
-              setMentorApplications(res?.data?.mentors);
+              setMentorApplications(filterByStatus<MentorApplication>(res.data.mentors, filter));
```
Comment (yellalena) [inline src/pages/ApplicationsPage/ui/ApplicationsPage.tsx]: is there some reason behind removing the `?`'s here?

**Review by yellalena — COMMENTED** [review]
couple of comments, but I would also like to run the app locally before final review

**Comment by yellalena** [comment]
when changing the tabs between "members" and "mentors", if any filter except "All" was selected - the switched tab is empty unless I manually re-select other filter.
maybe let's define the filter to be "All" by default on members/mentors tab switch
Screenshot 2026-01-25 at 18 53 04
?

File: src/pages/ApplicationsPage/ui/ApplicationsPage.tsx (hunk 1 above)
Comment (AnastasiaDevs) [reply src/pages/ApplicationsPage/ui/ApplicationsPage.tsx]: Done

File: src/pages/ApplicationsPage/ui/ApplicationsPage.tsx (hunk 2 above)
Comment (AnastasiaDevs) [reply src/pages/ApplicationsPage/ui/ApplicationsPage.tsx]: There’s a catch block, if the API returns a non-200 response or applications is missing, we log the error and sign out

File: src/pages/ApplicationsPage/ui/ApplicationsPage.tsx (hunk 3 above)
Comment (AnastasiaDevs) [reply src/pages/ApplicationsPage/ui/ApplicationsPage.tsx]: Fix

**Review by yellalena — APPROVED** [review]
looks good 🔥
